name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9,"3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check pending migrations
      run: |
        python manage.py makemigrations --check --dry-run
        python manage.py migrate
    
    # - name: Check pending static files to collect
    #   run: |
    #     python manage.py collectstatic --noinput
    #     git diff --exit-code static/
          
    - name: Lint with Flake8
      run: |
        flake8 --count --show-source --max-complexity=10 --max-line-length=130 --statistics --ignore=C901,F811
    - name: Run Tests
      run: |
        python manage.py test
